/**
 * @project:     PL/SQL DROP SCHEMA
 * @author:      Kamil Armatys, Vlad Udovychenko
 * @date:        19/12/2016
*/

DROP TABLE KA_DANE_DEMOGRAFICZNE;
DROP TABLE KA_KONTA;
DROP TABLE KA_SERWISY;
DROP TABLE KA_SESJE;
DROP TABLE KA_SYSTEMY;
DROP TABLE KA_UZYTKOWNICY;
DROP TABLE KA_ZRODLA;